services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args: &backend-args
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    environment: &backend-env
      SSL_MODE: "off"
      PHP_FPM_POOL_NAME: "tz_php"
      AUTORUN_ENABLED: false
    volumes:
      - .:/var/www/html
    ports:
      - "80:8080"
    restart: always

  php-cli:
    build:
      context: docker/php-cli
      dockerfile: Dockerfile
      args:
        <<: *backend-args
    environment:
      <<: *backend-env
      PHP_FPM_POOL_NAME: "tz_php_cli"
    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres:
